cloneWorkshops: false
contact:
- email: ''
  name: ''
dateStart: ''
description: ''
endDate: ''
event: ''
format: ''
herodescription: ''
institution: ''
location: ''
organizers:
- email: ''
  name: ''
sessions:
- date: ''
  description: ''
  helpers:
  - name: ''
  instructors:
  - name:
      email: ''
      name: ''
  location: ''
  time: ''
  title: jhb khjb
  workshop: ''
sponsors:
- link: ''
  name: ''
venue: ''
workshopsrepo: workshops
workshopsuser: dhri-curriculum
