cloneWorkshops: false
contact:
- email: ''
  name: ''
dateStart: ''
description: ''
endDate: ''
event: ''
format: ''
herodescription: ''
institution: ''
location: ''
organizers:
- email: ''
  name: ''
sessions:
- date: '2024-08-15'
  description: ''
  helpers:
  - name: ''
  instructors:
  - name:
      email: ''
      name: ''
  location: ''
  time: '20:29'
  title: lgjvljhbi;uhbui
  workshop: javascript
sponsors:
- link: ''
  name: ''
venue: ''
workshopsrepo: workshops
workshopsuser: dhri-curriculum
