cloneWorkshops: true
contact:
- email: ''
  name: ''
dateStart: '2025-12-02'
description: ygfhcikytghf
endDate: '2025-03-08'
event: nn
format: online
herodescription: gbv khjgv
institution: hkgjv
location: ''
organizers:
- email: ''
  name: ''
sessions:
- date: ''
  description: ''
  helpers:
  - name: ''
  instructors:
  - name:
      email: ''
      name: ''
  location: ''
  time: ''
  title: lukygoljyuhg
  workshop: ''
- date: ''
  description: ghvkujtygfv
  helpers:
  - name: ''
  instructors:
  - name:
      email: ''
      name: ''
  location: ''
  time: ''
  title: ghkfgdxsfjchlkijugh
  workshop: ''
sponsors:
- link: ''
  name: ''
venue: ''
workshopsrepo: DHRIFT-workshops
workshopsuser: szweibel
