cloneWorkshops: true
contact:
- email: ''
  name: ''
dateStart: '2025-02-01'
description: Hello
endDate: '2026-01-01'
event: Test
format: online
herodescription: hhh
institution: GC
location: ''
longDescription: Here is the long description
organizers:
- email: ''
  name: ''
sessions:
- date: ''
  description: ''
  helpers:
  - name: ''
  instructors:
  - name:
      email: ''
      name: ''
  location: ''
  time: ''
  title: ''
  workshop: ''
sponsors:
- link: ''
  name: ''
venue: ''
workshopsrepo: DHRIFT-workshops
workshopsuser: szweibel
