contact:
- email: contact@gc.cuny.edu
  name: Digital Research Institute
dateStart: '2025-01-01'
description: The Digital Research Institute is a week-long event that introduces participants
  to digital research methods and tools. Participants will learn how to use the command
  line, work with data, and create visualizations. The institute is open to all skill
  levels, from beginners to advanced users.
endDate: '2025-01-01'
event: Digital Research Institute
format: online
herodescription: Learn digital research methods and tools at the Digital Research
  Institute.
institution: CUNY Graduate Center
location: 365 5th Ave, New York, NY 10016
organizers:
- email: ''
  name: ''
sessions:
- date: '2023-03-01'
  description: This is the first day of the DHRI. We will introduce ourselves and
    the DHRI, and discuss the goals of the institute.
  helpers:
  - name: Zachary Lloyd
  instructors:
  - name:
      email: ''
      name: Steve Zweibel
  location: The Graduate Center, CUNY
  time: 09:00
  title: Welcome to the DHRI
  workshop: ''
- date: '2023-03-01'
  description: This workshop will introduce you to the command line, a text-based
    interface for interacting with your computer. We will cover basic commands, file
    management, and navigating the file system.
  helpers:
  - name: Zachary Lloyd
  instructors:
  - name:
      email: ''
      name: Stephen Zweibel
  location: The Graduate Center, CUNY
  time: '11:00'
  title: Introduction to the Command Line
  workshop: command-line
sponsors:
- link: https://gcdri.commons.gc.cuny.edu/
  name: GCDRI
- email: ''
  name: ''
venue: The Graduate Center, CUNY
workshopsrepo: workshops
workshopsuser: dhri-curriculum
