cloneWorkshops: false
contact:
- email: jane.doe@example.com
  name: Jane Doe
dateStart: '2024-09-01'
description: This is a description of the example event.
endDate: '2024-09-05'
event: Example Event
format: online
haveRegistration: true
herodescription: An example event for testing.
institution: Example Institute
location: Example Location
longdescription: This is a long description for the example event.
organizers:
- email: john.doe@example.com
  name: John Doe
registerLink: https://example.com/register
registerText: Register Now
sessions:
- date: '2024-09-01'
  description: This is a description of the example session.
  helpers:
  - name: Helper One
  instructors:
  - name:
      email: instructor.one@example.com
      name: Instructor One
  location: Example Location
  time: '10:00'
  title: Example Session
  workshop: Example Workshop
showWorkshops: false
socialMedia: Example Social Media
socialmedialink: https://example.com/social
sponsors:
- link: https://example.com
  name: Example Sponsor
venue: Example Venue
workshopsrepo: workshops
workshopsuser: dhri-curriculum
